import{S as b,a as E,i}from"./assets/vendor-89feecc5.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const h=document.querySelector(".js-search-form"),d=document.querySelector("input"),y=document.querySelector(".gallery"),q=document.querySelector(".loader"),x=document.querySelector(".js-loader"),f=document.querySelector(".more--btn"),m=document.querySelector(".non-existent");let a=1,u;const S=new b(".gallery a",{captions:!0,captionDelay:250,fadeSpeed:250,captionSelector:"img",captionsData:"alt",captionPosition:"bottom"});async function g(r,s){const e=new URLSearchParams({key:"41648594-e525389370aefc2e125a1a54e",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:r});try{const n=await E({method:"get",url:`https://pixabay.com/api/?${e}`});return n.data.hits.length<40&&p(),n}catch{p(),i.info({title:"Greetings!",message:"We're sorry, but you've reached the end of search results."})}}async function v(r,s){try{const e=await g(r,s);c(),a!==1?(y.insertAdjacentHTML("beforeend",w(e.data)),S.refresh()):(y.innerHTML=w(e.data),S.refresh())}catch{i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}}function w({hits:r}){return r.map(e=>`
    <li class="gallery__item">
    <a href="${e.largeImageURL}">
    <img class="gallery--img" src="${e.webformatURL}" alt="${e.tags}" title="${e.tags}"/>
    </a>
<ul class="gallery__list--characters">
  <p>likes: ${e.likes}</p>
  <p>views: ${e.views}</p>
  <p>comments: ${e.comments}</p>
  <p>downloads: ${e.downloads}</p>
</ul>
    </li>
    `).join("")}const c=()=>{q.classList.toggle("switcher")},L=()=>{x.classList.toggle("non-existent")},$=async()=>{try{if((await g(1,d.value)).data.hits.length===0)return p(),y.innerHTML="",i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});P()}catch{i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}};c();const p=()=>f.classList.add("switcher"),P=()=>f.classList.remove("switcher"),M=r=>(m.textContent=r,m.textContent);h.addEventListener("submit",r=>{r.preventDefault(),a=1,c(),v(1,d.value),$(),M(d.value),h.reset()});f.addEventListener("click",r=>{L(),a+=1,u=m.textContent,v(a,u),c(),L(),g(a+1,u)});
//# sourceMappingURL=commonHelpers.js.map
