import{S as w,i as u,a as b}from"./assets/vendor-89feecc5.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function t(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerpolicy&&(o.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?o.credentials="include":r.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=t(r);fetch(r.href,o)}})();const y=document.querySelector(".js-search-form"),f=document.querySelector("input"),d=document.querySelector(".gallery"),q=document.querySelector(".loader"),v=document.querySelector(".js-loader"),s=document.querySelector(".more--btn"),m=document.querySelector(".non-existent");let a=1,p;const g=new w(".gallery a",{captions:!0,captionDelay:250,fadeSpeed:250,captionSelector:"img",captionsData:"alt",captionPosition:"bottom"});async function x(e,n){const t=new URLSearchParams({key:"41648594-e525389370aefc2e125a1a54e",q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:e});try{return await b({method:"get",url:`https://pixabay.com/api/?${t}`})}catch{return!1}}async function S(e,n){try{const t=await x(e,n);c(),E(t),a!==1?(d.insertAdjacentHTML("beforeend",h(t.data)),g.refresh()):(d.innerHTML=h(t.data),g.refresh()),_()}catch{}}function h({hits:e}){return e.map(t=>`
    <li class="gallery__item">
    <a href="${t.largeImageURL}">
    <img class="gallery--img" src="${t.webformatURL}" alt="${t.tags}" title="${t.tags}"/>
    </a>
<ul class="gallery__list--characters">
  <p>likes: ${t.likes}</p>
  <p>views: ${t.views}</p>
  <p>comments: ${t.comments}</p>
  <p>downloads: ${t.downloads}</p>
</ul>
    </li>
    `).join("")}const E=e=>{try{if(a===13)return s.classList.add("switcher"),u.info({title:"Hey!",message:"Sorry, there are no more images matching your search query. Please try find some another photo!"});if(e.data.hits.length<40)return s.classList.add("switcher"),u.info({title:"Hey!",message:"Sorry, there are no more images matching your search query."});if(e.data.hits.length===0)return s.classList.add("switcher"),d.innerHTML="",u.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});s.classList.remove("switcher")}catch{}},$=e=>(m.textContent=e,m.textContent),c=()=>{q.classList.toggle("switcher")},L=()=>{v.classList.toggle("non-existent")};function I(){const e=document.querySelector(".gallery__item");return e?e.getBoundingClientRect().height:0}function _(){const e=I();e>0&&window.scrollBy({top:e*2,left:0,behavior:"smooth"})}c();y.addEventListener("submit",e=>{e.preventDefault(),a=1,c(),S(1,f.value),$(f.value),y.reset()});s.addEventListener("click",e=>{L(),a+=1,p=m.textContent,S(a,p),c(),L()});
//# sourceMappingURL=commonHelpers.js.map
